apiVersion: apps/v1
kind: Deployment
metadata:
  name: cameras-ap
  namespace: efficient-edge-demo
  labels:
    infra: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      infra: ap
  template:
    metadata:
      labels:
        infra: ap
    spec:
      hostNetwork: true
      serviceAccountName: efficient-edge-demo-sa  
      containers:
      - name: camwifi-ap
        image: quay.io/oglok/cam-ap:agx
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true # otherwise hostapd can't change channels for some reason
          runAsRoot: true
          runAsUser: 0
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW

