apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efficient-edge-demo-cr
  namespace: efficient-edge-demo
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
