apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: efficient-edge-demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webserver
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: efficient-edge-demo
spec:
  host: microshift-web-demo.local
  port:
    targetPort: 5000
  to:
    kind: Service
    name: webserver
    weight: 100
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: efficient-edge-demo
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver 
        image: quay.io/alexander_mevec/efficient-edge-demo:webserver
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
          - name: flask-port
            containerPort: 5000
#        command: ["sleep"]
#        args: ["infinity"]
        startupProbe:
          httpGet:
            path: /healthy
            port: flask-port
          failureThreshold: 100
          periodSeconds: 5
